"""One-off script to regenerate data/routing_guide.json from memo content."""
import json
from pathlib import Path

ITEMS = [
    (1, "Summary", "Project overview, resource/reserve statement, economics, key risks, and recommendations.", "Is this project viable at a high level?"),
    (2, "Introduction", "Report terms, issuer identity, QP identity, effective date, and site visit details.", "Who prepared the report and is the QP qualified for this commodity?"),
    (3, "Reliance on Other Experts", "Legal, tenure, tax, environment, and permitting reliance statements.", "Are there unverified assumptions from non-geological experts?"),
    (4, "Property Description and Location", "Tenure, ownership, royalties, NSR, government interest, permits, and encumbrances.", "Is tenure secure? What royalties and encumbrances apply?"),
    (5, "Accessibility, Climate, Infrastructure", "Roads, rail, port, power, water, climate, labour, and logistics.", "Are infrastructure constraints underestimated?"),
    (6, "History", "Historical ownership, exploration, production, and historical estimates.", "Is historical data being relied upon without proper verification?"),
    (7, "Geological Setting and Mineralization", "Regional/local geology, host rocks, alteration, mineralization style, and controls.", "Is the geological model sound and the deposit well understood?"),
    (8, "Deposit Types", "Genetic model and analogue deposit type.", "Is the deposit type correctly identified? Are the analogues appropriate?"),
    (9, "Exploration", "Mapping, geochemistry, geophysics, trenching, and sampling.", "Is there genuine exploration upside beyond the defined resource?"),
    (10, "Drilling", "Drill type, spacing, orientation, recovery, survey, and intercept quality.", "Is the database sufficient for the reported classification?"),
    (11, "Sample Preparation, Analyses and Security", "Lab, method, QAQC program, CRM/blank/duplicate rates, and security.", "Is the assay data reliable and the QAQC protocol fit for purpose?"),
    (12, "Data Verification", "QP validation, database integrity, site visit, and independent checks.", "Has an independent QP validated the database?"),
    (13, "Mineral Processing and Metallurgical Testing", "Testwork, ore types, recovery, process route, and deleterious elements.", "Are the recovery assumptions supported by adequate testwork?"),
    (14, "Mineral Resource Estimates", "Resource statement, cut-off, estimation method, variography, classification, and density.", "Is the resource estimate defensible and correctly classified?"),
    (15, "Mineral Reserve Estimates", "Reserve statement, modifying factors, cut-off, and Proven/Probable split.", "Is the reserve conversion ratio and modifying factor set reasonable?"),
    (16, "Mining Methods", "Pit/UG design, dilution, recovery, geotech, and production schedule.", "Is the mining method and schedule realistic for this deposit?"),
    (17, "Recovery Methods", "Processing plant, flowsheet, throughput, recovery, and reagents.", "Is the processing design appropriate for the ore type?"),
    (18, "Project Infrastructure", "Roads, power, water, tailings, waste dump, port, and logistics.", "Are infrastructure costs fully scoped and risks identified?"),
    (19, "Market Studies and Contracts", "Payability, concentrate terms, product pricing, and offtake contracts.", "Are price, payability, and TC/RC assumptions reasonable?"),
    (20, "Environmental Studies, Permitting and Social Impact", "Baseline, permits, closure, community, ESG, and resettlement.", "Are permitting and ESG risks adequately characterised?"),
    (21, "Capital and Operating Costs", "CAPEX, OPEX, cost basis, accuracy class, and contingencies.", "Do costs reflect study-stage accuracy and peer benchmarks?"),
    (22, "Economic Analysis", "NPV, IRR, payback, sensitivity, discount rate, tax, and royalty.", "Are the economic assumptions appropriate and the NPV defensible?"),
    (23, "Adjacent Properties", "Nearby deposits and mines, and analogues.", "What do adjacent projects tell us about geological risk and opportunity?"),
    (24, "Other Relevant Data and Information", "Project-specific technical material.", "Is there additional technical data relevant to the investment?"),
    (25, "Interpretation and Conclusions", "QP conclusions, risks, confidence, and project materiality.", "What are the QP's own stated risks and confidence limitations?"),
    (26, "Recommendations", "Work program, budget, and next-stage studies.", "What does the QP say is required before the next study stage?"),
    (27, "References", "Source reports and citations.", "Are references credible, current, and properly cited?"),
]

QUERY_LOOKUP = [
    ("cut-off grade", [14, 15, 22], []),
    ("cutoff grade", [14, 15, 22], []),
    ("open pit vs underground cut", [14, 15, 16, 21], []),
    ("open pit cut-off", [14, 15, 16, 21], []),
    ("underground cut-off", [14, 15, 16, 21], []),
    ("nsr cut-off", [14, 15, 19, 22], []),
    ("net smelter return", [14, 15, 19, 22], []),
    ("deposit type analogue", [7, 8, 23], []),
    ("closest analogue", [7, 8, 23], []),
    ("resource classification", [14, 10, 12], []),
    ("classification defensible", [14, 10, 12], []),
    ("drill spacing", [10, 14], [12]),
    ("qaqc", [11, 12], []),
    ("quality assurance", [11, 12], []),
    ("density", [14, 11, 12], []),
    ("specific gravity", [14, 11, 12], []),
    ("metallurgical recover", [13, 17], []),
    ("recovery assumption", [13, 17], []),
    ("deleterious element", [13, 14, 19], []),
    ("mining method", [16, 15], []),
    ("dilution", [15, 16], []),
    ("mining recovery", [15, 16], []),
    ("capex", [21, 16, 17, 18], []),
    ("opex", [21, 16, 17, 18], []),
    ("capital cost", [21, 16, 17, 18], []),
    ("operating cost", [21, 16, 17, 18], []),
    ("economic assumption", [22, 19, 21], []),
    ("npv", [22, 19, 21], []),
    ("irr", [22, 19, 21], []),
    ("country risk", [4, 5, 20, 25], []),
    ("jurisdictional risk", [4, 5, 20, 25], []),
    ("esg", [20, 4, 25], []),
    ("permitting", [20, 4, 25], []),
    ("social license", [20, 4, 25], []),
    ("red flag", [25, 1, 26], []),
    ("technical red flag", [25, 1, 26], []),
    ("next study stage", [26, 25], []),
    ("recommendation", [26, 25], []),
    ("historical data", [6, 12], [14]),
    ("prior estimate", [6, 12], [14]),
    ("tenure", [4], [3, 20]),
    ("royalty", [4], [19, 22]),
    ("qualified person", [2], [25]),
    ("go or no-go", [25, 26, 1], []),
    ("peer benchmark", [14, 15, 22], []),
    ("comparable project", [7, 8, 23], []),
]

ROUTING_MATRICES = {
    "4": {
        "search": "Item 4: Property Description and Location.",
        "cross_check": [3, 20],
        "extract": [
            "Licence, claim or concession name.", "Ownership and joint-venture structure.",
            "Royalties and net smelter return interests.", "Government or state ownership interests.",
            "Surface-access rights.", "Water rights.", "Environmental liabilities.",
        ],
        "compare": ["Compare tenure conditions with similar projects in the same country or region."],
        "flag": ["Near-term licence expiry.", "Excessive royalty burden.", "Unresolved ownership."],
    },
    "5": {
        "search": "Item 5: Accessibility, Climate, Local Resources, Infrastructure and Physiography.",
        "cross_check": [18, 21],
        "extract": ["Road access.", "Grid and onsite power availability.", "Water sources.", "Climate constraints.", "Seasonal access restrictions."],
        "compare": ["Compare infrastructure with projects in similar geographic settings."],
        "flag": ["Underestimated logistics risks.", "Power-supply constraints.", "Water-supply constraints."],
    },
    "7-8": {
        "search": "Item 7: Geological Setting and Mineralization; Item 8: Deposit Types.",
        "cross_check": [23],
        "extract": ["Regional geological setting.", "Deposit type.", "Mineralisation style.", "Orebody geometry.", "Structural controls."],
        "compare": ["Search and rank analogues by deposit type, commodity, host rock, mineralisation style."],
        "flag": ["Deposit type misidentified.", "Inappropriate analogues."],
    },
    "10": {
        "search": "Item 10: Drilling.",
        "cross_check": [14],
        "extract": ["Total drill holes.", "Drill spacing.", "Core recovery.", "Downhole-survey method.", "Areas of sparse drilling."],
        "compare": ["Assess whether drilling supports Measured, Indicated and Inferred classification."],
        "flag": ["Excessive extrapolation.", "Low core recovery.", "Classification unsupported by drill density."],
    },
    "11-12": {
        "search": "Item 11: Sample Preparation, Analyses and Security; Item 12: Data Verification.",
        "cross_check": [],
        "extract": ["CRM insertion rate.", "Blank insertion rate.", "Duplicate insertion rate.", "Laboratory accreditation.", "QP site visit."],
        "compare": ["Compare protocols with similar NI 43-101 projects."],
        "flag": ["Missing QAQC records.", "Inadequate insertion rates.", "Heavy reliance on unverified historical data."],
    },
    "13-17": {
        "search": "Item 13: Mineral Processing and Metallurgical Testing; Item 17: Recovery Methods.",
        "cross_check": [],
        "extract": ["Testwork programme.", "Recovery by ore type.", "Processing route.", "Deleterious elements.", "Variability testing."],
        "compare": ["Benchmark against commodity, ore type, deposit type, processing route."],
        "flag": ["High recovery based on limited testing.", "Inadequate variability testing.", "Unresolved deleterious-element issues."],
    },
    "14": {
        "search": "Item 14: Mineral Resource Estimates.",
        "cross_check": [10, 12],
        "extract": ["Resource statement.", "Cut-off grade.", "Estimation method.", "Classification criteria.", "Density assumptions."],
        "compare": ["Benchmark cut-off grade, estimation method, classification criteria against peers."],
        "flag": ["Aggressive cut-off assumptions.", "Classification inconsistent with drill spacing.", "Unsupported density."],
    },
    "15-16": {
        "search": "Item 15: Mineral Reserve Estimates; Item 16: Mining Methods.",
        "cross_check": [],
        "extract": ["Reserve statement.", "Dilution.", "Mining recovery.", "Mining method.", "Strip ratio.", "Production rate."],
        "compare": ["Benchmark reserve conversion, dilution, mining recovery against peers."],
        "flag": ["High reserve-conversion ratio.", "Low dilution.", "Inferred material included in reserves."],
    },
    "19-21-22": {
        "search": "Item 19: Market Studies; Item 21: Capital and Operating Costs; Item 22: Economic Analysis.",
        "cross_check": [],
        "extract": ["Metal-price assumptions.", "NPV.", "IRR.", "Initial CAPEX.", "OPEX.", "Sensitivity results."],
        "compare": ["Compare peer projects by commodity, country, mining method, study stage."],
        "flag": ["Aggressive metal prices.", "Low contingency.", "Optimistic operating cost.", "Inadequate sensitivity analysis."],
    },
    "20": {
        "search": "Item 20: Environmental Studies, Permitting and Social or Community Impact.",
        "cross_check": [4],
        "extract": ["Required permits.", "Permit status.", "Closure plan.", "Community agreements.", "Environmental liabilities."],
        "compare": ["Compare with similar projects in the same jurisdiction."],
        "flag": ["Missing key permits.", "Inadequate closure provision.", "Community opposition."],
    },
    "25-26": {
        "search": "Item 25: Interpretation and Conclusions; Item 26: Recommendations.",
        "cross_check": [1],
        "extract": ["QP principal conclusions.", "Material technical risks.", "Recommended work programme.", "Recommended budget."],
        "compare": ["Assess report tone: conservative, balanced, or promotional."],
        "flag": ["Risks disclosed in body but omitted from conclusions.", "Overly positive language unsupported by data."],
    },
}

BENCHMARK_TEMPLATES = [
    {"name": "Cut-off Grade Benchmarking", "keywords": ["cut-off grade benchmark", "cutoff grade benchmark", "typical cut-off"], "search_criteria": ["commodity", "country", "deposit_type"], "extract_fields": ["resource_cutoff", "reserve_cutoff", "nsr_cutoff", "metal_price", "study_stage"], "output_format": "typical range, median, outliers, reasonableness assessment"},
    {"name": "Open-Pit Cut-off Grade Reasonableness", "keywords": ["open pit cut-off", "open-pit cut-off reasonable"], "search_criteria": ["commodity", "deposit_type", "mining_method"], "extract_fields": ["cutoff_grade", "metal_price", "mining_cost", "processing_cost", "recovery"], "output_format": "peer comparison table and reasonableness verdict"},
    {"name": "Underground Cut-off Grade Benchmark", "keywords": ["underground cut-off", "underground cutoff benchmark"], "search_criteria": ["commodity", "mining_method"], "extract_fields": ["resource_cutoff", "reserve_cutoff", "mining_cost", "dilution"], "output_format": "normal range and outlier identification"},
    {"name": "NSR Cut-off Benchmark", "keywords": ["nsr cut-off benchmark", "nsr cutoff", "nsr cut-off", "nsr cutoff benchmark"], "search_criteria": ["commodity", "cutoff_type"], "extract_fields": ["nsr_cutoff", "metal_prices", "recoveries", "payability"], "output_format": "NSR cut-off comparison across peers"},
    {"name": "Estimation Method Benchmark", "keywords": ["estimation method benchmark", "estimation method commonly"], "search_criteria": ["commodity", "deposit_type"], "extract_fields": ["estimation_method", "composite_length", "capping", "block_size", "classification_criteria"], "output_format": "method summary vs target project"},
    {"name": "Classification Criteria Benchmark", "keywords": ["classification criteria benchmark", "measured indicated inferred criteria"], "search_criteria": ["commodity", "deposit_type"], "extract_fields": ["drill_spacing", "classification_criteria", "geological_confidence"], "output_format": "classification rules comparison"},
    {"name": "QAQC Benchmark", "keywords": ["qaqc benchmark", "qaqc protocol typical"], "search_criteria": ["commodity"], "extract_fields": ["crm_rate", "blank_rate", "duplicate_rate", "lab_accreditation"], "output_format": "protocol comparison vs NI 43-101 practice"},
    {"name": "Density Benchmark", "keywords": ["density benchmark", "specific gravity benchmark"], "search_criteria": ["commodity", "deposit_type", "ore_type"], "extract_fields": ["density_values", "measurement_method", "sample_count"], "output_format": "density assumptions comparison"},
    {"name": "Metallurgical Recovery Benchmark", "keywords": ["metallurgical recovery benchmark", "recovery benchmark"], "search_criteria": ["commodity", "deposit_type", "ore_type"], "extract_fields": ["recovery", "processing_route", "head_grade", "testwork_stage"], "output_format": "typical recovery ranges vs target"},
    {"name": "Mining Method Benchmark", "keywords": ["mining method benchmark", "mining method appropriate"], "search_criteria": ["commodity", "deposit_geometry", "mining_method"], "extract_fields": ["mining_method", "dilution", "mining_recovery", "strip_ratio", "production_rate"], "output_format": "method alignment assessment"},
    {"name": "CAPEX/OPEX Benchmark", "keywords": ["capex opex benchmark", "capital cost benchmark", "operating cost benchmark"], "search_criteria": ["commodity", "deposit_type", "mining_method", "processing_route"], "extract_fields": ["initial_capex", "opex", "sustaining_capex", "unit_costs"], "output_format": "normalized cost comparison"},
    {"name": "Country Risk Benchmark", "keywords": ["country risk benchmark", "jurisdictional risk"], "search_criteria": ["country"], "extract_fields": ["permitting_risks", "community_risks", "political_risks", "infrastructure_risks"], "output_format": "country-specific risk summary"},
    {"name": "Technical Red Flag Detection", "keywords": ["red flag", "technical red flag"], "search_criteria": ["target_report"], "extract_fields": ["cutoff", "metal_price", "recovery", "qaqc", "density", "classification", "capex", "sensitivity"], "output_format": "list of red flags with evidence"},
]

CORE_DD_QUESTIONS = [
    "What are the closest NI 43-101 analogues for this project?",
    "What cut-off grades are used by comparable projects?",
    "Are the metal price assumptions reasonable compared with peer reports?",
    "Are recovery assumptions supported by comparable metallurgy?",
    "Is the Mineral Resource classification justified by drill spacing and continuity?",
    "Is the Reserve conversion ratio reasonable?",
    "Are dilution and mining recovery assumptions realistic?",
    "Are CAPEX and OPEX within peer range?",
    "Is the selected mining method appropriate for the geometry?",
    "Is the selected processing route appropriate for ore type?",
    "Are deleterious elements properly tested and modelled?",
    "Are density assumptions adequate and representative?",
    "Are QAQC results sufficient for resource reporting?",
    "Are there unresolved historical data risks?",
    "Are there environmental or permitting risks common to this jurisdiction?",
    "What are the main technical red flags compared with peer reports?",
    "What assumptions are aggressive or unsupported?",
    "What additional data is required before investment decision?",
    "Is the project consistent with a PEA, PFS, FS, or investment-grade standard?",
    "Should the project be classified as Go, Conditional Go, Further Work, or No-Go?",
]

METADATA_SCHEMA = {
    "report_item": "Item number and section title (e.g. Item 14 Mineral Resource Estimates)",
    "commodity": "Cu, Au, Zn, Pb, Ag, Ni, Li, REE",
    "country": "Russia, Canada, Peru, Zambia",
    "region": "CIS, Andes, West Africa, Arctic",
    "deposit_type": "Porphyry, VMS, skarn, IOCG, sediment-hosted",
    "mining_method": "Open pit, underground, combined",
    "processing_route": "Flotation, leach, CIL, heap leach",
    "study_stage": "Exploration, MRE, PEA, PFS, FS, operating",
    "ore_type": "Oxide, transition, sulphide, fresh",
    "cutoff_type": "Grade cut-off, NSR cut-off, pit shell",
    "economic_year": "Price/cost assumption year",
    "source_report_date": "Technical report date",
    "effective_date": "Effective date of resource/reserve",
}

data = {
    "version": "1.0",
    "source": "BMRC MRE Chapter Routing Guide for NI 43-101 Technical Reports (2026-06-16)",
    "items": [
        {"number": n, "title": t, "gather_fields": [g], "dd_question": q}
        for n, t, g, q in ITEMS
    ],
    "query_lookup": [
        {"question_pattern": pat, "primary_items": prim, "cross_check_items": cross}
        for pat, prim, cross in QUERY_LOOKUP
    ],
    "routing_matrices": ROUTING_MATRICES,
    "benchmark_templates": BENCHMARK_TEMPLATES,
    "core_dd_questions": CORE_DD_QUESTIONS,
    "metadata_schema": METADATA_SCHEMA,
}

out = Path(__file__).parent / "data" / "routing_guide.json"
out.write_text(json.dumps(data, indent=2, ensure_ascii=True), encoding="utf-8")
print(f"Wrote {out}")
